AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 16
INCLUDE_TOP: False
<<<<<<< HEAD
EPOCHS: 50
=======
EPOCHS: 150
>>>>>>> 094c4478fa745d700a4c220af87a284e1b2987eb
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
